### PR TITLE
fix(headers): avoid double spaces in the headers

### PR DESCRIPTION
**Pull request by yacir**
it fixes https://github.com/lettre/lettre/issues/949

### CODE REVIEW

**Review by paolobarbolini — APPROVED** [review]
LGTM. Thank you for the fix.
Could you add a regression test?

**Comment by yacir** [comment]
Thanks for the quick answer. Was thinking to add them later to the letter crate here https://github.com/lettre/lettre/blob/master/src/message/header/mod.rs but you're right i ll add it here

**Comment by yacir** [comment]
@paolobarbolini test added. Let me know if it's okay for you 
thanks

**Comment by paolobarbolini** [comment]
Turns out this doesn't work as I'd have originally expected.

`new_line_and_space` is just a silly micro-optimization that looking back doesn't make sense and I'm thinking of removing. Anyway the way it should work is the same as:

```diff
diff --git a/src/headers/writer.rs b/src/headers/writer.rs
index a36e6ab..0e024c5 100644
--- a/src/headers/writer.rs
+++ b/src/headers/writer.rs
@@ -55,11 +55,8 @@ impl<'a> EmailWriter<'a> {
 
     /// Equivalent to calling `new_line()` and `space()` consecutively.
     pub(crate) fn new_line_and_space(&mut self) -> fmt::Result {
-        self.spaces = 0;
-        self.writer.write_str("\r\n ")?;
-        self.line_len = 1;
-        self.optional_breakpoint = false;
-        self.can_go_to_new_line_now = false;
+        self.new_line()?;
+        self.space();
 
         Ok(())
     }
```

Doing so would break your test, so I'd have to also do:

```diff
diff --git a/src/headers/writer.rs b/src/headers/writer.rs
index a36e6ab..a418231 100644
--- a/src/headers/writer.rs
+++ b/src/headers/writer.rs
@@ -45,6 +45,7 @@ impl<'a> EmailWriter<'a> {
 
     /// Go to a new line and reset the `line_len` to `0`.
     pub fn new_line(&mut self) -> fmt::Result {
+        self.spaces = 0;
         self.writer.write_str("\r\n")?;
         self.line_len = 0;
         self.optional_breakpoint = false;
```

Which breaks many other tests.

**Comment by paolobarbolini** [comment]
While it produces an ugly output this should now be fixed by c128b46abd8685fb22cd91a925d3bba35cd746f7

**Comment by yacir** [comment]
it's much better now, i ll give a try with my dataset to check if it fixes all the previous failing cases

**Comment by yacir** [comment]
@paolobarbolini i tested with +3400 real use case. 
| https://github.com/lettre/email-encoding/releases/tag/v0.2.1 | https://github.com/lettre/email-encoding/commit/14104c336553b5c1b26f463dff78764f813099d7 or https://github.com/lettre/email-encoding/pull/8  |
| ---- | ---- |
| 456 encoding errors | 6 remaining encoding errors | 

It's way better, but we still have some corner cases

**Comment by paolobarbolini** [comment]
Nice. I'm thinking of making a new release and handle any other report separately

**Comment by yacir** [comment]
I also think it's the best compromise since it fixes ~99% of the errors

**Pull request merged**
