### PR TITLE
rfc2231: Add unit test for hex encoded chars line folding

### PR DESCRIPTION
**Pull request by thomasjfox**
The new unit test creates a "filename" by appending 'Ü' to it up to 256 times.
This character needs to be encoded and we verify multiple conditions:

* no hex encoded char is split across the header line folding
* the amount of outputted hex encoded chars matches the
  expected number of 'Ü' characters we input.
* max line length is respected at all times.

To spice things up, all of this is also verified with
varying single byte start offsets like "x", "xx" or "xxx".

### CODE REVIEW

**Comment by thomasjfox** [comment]
Here is how debug output for "i == 99" looks like:

Content-Disposition: attachment;
 filename*0*=utf-8''%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*1*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*2*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*3*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*4*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*5*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*6*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*7*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*8*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*9*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*10*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*11*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*12*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C

Content-Disposition: attachment;
 filename*0*=utf-8''x%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*1*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*2*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*3*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*4*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*5*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*6*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*7*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*8*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*9*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*10*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*11*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C;
 filename*12*=%C3%9C%C3%9C%C3%9C%C3%9C%C3%9C

(start offset 'xx' and 'xxx' are skipped here)

The line length verification code has also been tested by messing up the encoder:
```
--- a/src/headers/rfc2231.rs
+++ b/src/headers/rfc2231.rs
@@ -71,7 +71,7 @@ pub fn encode(key: &str, mut value: &str, w: &mut EmailWriter) -> fmt::Result {
             }
 
             let mut chars = value.chars();
-            while w.line_len() < MAX_LINE_LEN - "=xx=xx=xx=xx;\r\n".len() {
+            while w.line_len() < MAX_LINE_LEN + 10 - "=xx=xx=xx=xx;\r\n".len() {
                 match chars.next() {
                     Some(c) => {
                         hex_encoding::percent_encode_char(w, c)?;
```
-> this fails the unit test, too.

Overall the unit test should be robust to verify a future refactoring doesn't break anything.

**Review by paolobarbolini — APPROVED** [review]
Thank you very much for the PR! Can you fix the 1.52 incompatibility?

We can ignore the clippy fail, as it was already broken before.

**Comment by thomasjfox** [comment]
> Thank you very much for the PR! Can you fix the 1.52 incompatibility?

sure, I'll look into it tomorrow. Once it's fixed, I'll force-push the branch.

> We can ignore the clippy fail, as it was already broken before.

yes and I always make sure my code is "clippy clean" :) Hopefully adapting the code for 1.52 will not issue clippy warnings on 1.56, but we'll see.

**Comment by thomasjfox** [comment]
The fix for three compiler warnings on 1.52.1 was embarrassingly simple:
```diff
--- a/src/headers/rfc2231.rs
+++ b/src/headers/rfc2231.rs
@@ -241,7 +241,7 @@ mod tests {
         let base_header = "Content-Disposition: attachment;".to_string();
         let line_len = base_header.len();
 
-        for start_offset in ["", "x", "xx", "xxx"] {
+        for start_offset in &["", "x", "xx", "xxx"] {
```
Feel free to tweak the code or commit message any other way.

**Pull request merged**
